# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "pytube" = super.buildPythonPackage rec {
    pname = "pytube";
    version = "12.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/30/b4b72a27c2b4bca2a03a82435a5b29e6bc33a7ea7c9f277ba6ecb1dc663e/pytube-12.1.0-py3-none-any.whl";
      sha256 = "1nnqyk2kjvckspjy41psxj3x53grnjk5f5c8gwl4rjlyvzzv3r62";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "youtube-dl" = super.buildPythonPackage rec {
    pname = "youtube-dl";
    version = "2021.12.17";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/93/65c208f51895f74bbfea1423974c54fff1d1c4e9a97ebee1011b021554b8/youtube_dl-2021.12.17-py2.py3-none-any.whl";
      sha256 = "0mfdg6fwdw8fqpsqy102dz3rxrbq4mqw1cs798vf0iw6wrfnsczi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
